// Database types generated from Supabase
// This file contains type definitions for the HRM database

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          tax_id: string | null;
          registration_number: string | null;
          currency_code: string;
          timezone: string;
          subscription_plan: string;
          subscription_status: string;
          max_employees: number;
          settings: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          tax_id?: string | null;
          registration_number?: string | null;
          currency_code?: string;
          timezone?: string;
          subscription_plan?: string;
          subscription_status?: string;
          max_employees?: number;
          settings?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          tax_id?: string | null;
          registration_number?: string | null;
          currency_code?: string;
          timezone?: string;
          subscription_plan?: string;
          subscription_status?: string;
          max_employees?: number;
          settings?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      company_admins: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          role: string;
          permissions: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          role?: string;
          permissions?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string;
          role?: string;
          permissions?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          company_id: string | null;
          employee_code: string | null;
          first_name: string;
          last_name: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          alternate_phone: string | null;
          personal_email: string | null;
          date_of_birth: string | null;
          gender: string | null;
          nationality: string;
          nic_number: string | null;
          passport_number: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string;
          postal_code: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_relationship: string | null;
          avatar_url: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id?: string | null;
          employee_code?: string | null;
          first_name: string;
          last_name?: string | null;
          email: string;
          phone?: string | null;
          alternate_phone?: string | null;
          personal_email?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string;
          nic_number?: string | null;
          passport_number?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relationship?: string | null;
          avatar_url?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_id?: string | null;
          employee_code?: string | null;
          first_name?: string;
          last_name?: string | null;
          email?: string;
          phone?: string | null;
          alternate_phone?: string | null;
          personal_email?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string;
          nic_number?: string | null;
          passport_number?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relationship?: string | null;
          avatar_url?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      branches: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          code: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          is_headquarters: boolean;
          is_active: boolean;
          work_start_time: string;
          work_end_time: string;
          working_days: string[];
          latitude: number | null;
          longitude: number | null;
          location_radius_meters: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          code?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          is_headquarters?: boolean;
          is_active?: boolean;
          work_start_time?: string;
          work_end_time?: string;
          working_days?: string[];
          latitude?: number | null;
          longitude?: number | null;
          location_radius_meters?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          code?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          is_headquarters?: boolean;
          is_active?: boolean;
          work_start_time?: string;
          work_end_time?: string;
          working_days?: string[];
          latitude?: number | null;
          longitude?: number | null;
          location_radius_meters?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      departments: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          code: string | null;
          description: string | null;
          parent_department_id: string | null;
          department_head_id: string | null;
          branch_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          code?: string | null;
          description?: string | null;
          parent_department_id?: string | null;
          department_head_id?: string | null;
          branch_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          code?: string | null;
          description?: string | null;
          parent_department_id?: string | null;
          department_head_id?: string | null;
          branch_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      designations: {
        Row: {
          id: string;
          company_id: string;
          department_id: string | null;
          title: string;
          code: string | null;
          description: string | null;
          level: number;
          min_salary: number | null;
          max_salary: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          department_id?: string | null;
          title: string;
          code?: string | null;
          description?: string | null;
          level?: number;
          min_salary?: number | null;
          max_salary?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          department_id?: string | null;
          title?: string;
          code?: string | null;
          description?: string | null;
          level?: number;
          min_salary?: number | null;
          max_salary?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      roles: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          description: string | null;
          is_system_role: boolean;
          permissions: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          description?: string | null;
          is_system_role?: boolean;
          permissions?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          description?: string | null;
          is_system_role?: boolean;
          permissions?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      employees: {
        Row: {
          id: string;
          profile_id: string;
          company_id: string;
          employee_code: string;
          department_id: string | null;
          designation_id: string | null;
          branch_id: string | null;
          reporting_manager_id: string | null;
          employment_type: string;
          date_of_joining: string;
          date_of_leaving: string | null;
          probation_end_date: string | null;
          confirmation_date: string | null;
          notice_period_days: number;
          work_start_time: string;
          work_end_time: string;
          working_hours_per_day: number;
          working_days: string[];
          bank_name: string | null;
          bank_branch: string | null;
          bank_account_number: string | null;
          bank_account_name: string | null;
          epf_number: string | null;
          etf_number: string | null;
          status: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          company_id: string;
          employee_code: string;
          department_id?: string | null;
          designation_id?: string | null;
          branch_id?: string | null;
          reporting_manager_id?: string | null;
          employment_type?: string;
          date_of_joining: string;
          date_of_leaving?: string | null;
          probation_end_date?: string | null;
          confirmation_date?: string | null;
          notice_period_days?: number;
          work_start_time?: string;
          work_end_time?: string;
          working_hours_per_day?: number;
          working_days?: string[];
          bank_name?: string | null;
          bank_branch?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          epf_number?: string | null;
          etf_number?: string | null;
          status?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          profile_id?: string;
          company_id?: string;
          employee_code?: string;
          department_id?: string | null;
          designation_id?: string | null;
          branch_id?: string | null;
          reporting_manager_id?: string | null;
          employment_type?: string;
          date_of_joining?: string;
          date_of_leaving?: string | null;
          probation_end_date?: string | null;
          confirmation_date?: string | null;
          notice_period_days?: number;
          work_start_time?: string;
          work_end_time?: string;
          working_hours_per_day?: number;
          working_days?: string[];
          bank_name?: string | null;
          bank_branch?: string | null;
          bank_account_number?: string | null;
          bank_account_name?: string | null;
          epf_number?: string | null;
          etf_number?: string | null;
          status?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      attendance: {
        Row: {
          id: string;
          employee_id: string;
          company_id: string;
          attendance_date: string;
          status: string;
          check_in_time: string | null;
          check_out_time: string | null;
          check_in_latitude: number | null;
          check_in_longitude: number | null;
          check_out_latitude: number | null;
          check_out_longitude: number | null;
          check_in_location: string | null;
          check_out_location: string | null;
          total_work_hours: number;
          total_break_hours: number;
          overtime_hours: number;
          is_late: boolean;
          late_minutes: number;
          late_reason: string | null;
          is_early_leave: boolean;
          early_leave_minutes: number;
          early_leave_reason: string | null;
          notes: string | null;
          source: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          employee_id: string;
          company_id: string;
          attendance_date: string;
          status?: string;
          check_in_time?: string | null;
          check_out_time?: string | null;
          check_in_latitude?: number | null;
          check_in_longitude?: number | null;
          check_out_latitude?: number | null;
          check_out_longitude?: number | null;
          check_in_location?: string | null;
          check_out_location?: string | null;
          total_work_hours?: number;
          total_break_hours?: number;
          overtime_hours?: number;
          is_late?: boolean;
          late_minutes?: number;
          late_reason?: string | null;
          is_early_leave?: boolean;
          early_leave_minutes?: number;
          early_leave_reason?: string | null;
          notes?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          employee_id?: string;
          company_id?: string;
          attendance_date?: string;
          status?: string;
          check_in_time?: string | null;
          check_out_time?: string | null;
          check_in_latitude?: number | null;
          check_in_longitude?: number | null;
          check_out_latitude?: number | null;
          check_out_longitude?: number | null;
          check_in_location?: string | null;
          check_out_location?: string | null;
          total_work_hours?: number;
          total_break_hours?: number;
          overtime_hours?: number;
          is_late?: boolean;
          late_minutes?: number;
          late_reason?: string | null;
          is_early_leave?: boolean;
          early_leave_minutes?: number;
          early_leave_reason?: string | null;
          notes?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      leave_types: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          code: string | null;
          type: string;
          description: string | null;
          default_days_per_year: number;
          is_carry_forward: boolean;
          max_carry_forward_days: number;
          carry_forward_expiry_months: number;
          accrual_frequency: string | null;
          accrual_day: number;
          min_notice_days: number;
          max_consecutive_days: number | null;
          is_half_day_allowed: boolean;
          requires_document: boolean;
          document_required_after_days: number | null;
          requires_manager_approval: boolean;
          requires_hr_approval: boolean;
          applicable_gender: string[] | null;
          is_paid: boolean;
          pay_percentage: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          code?: string | null;
          type: string;
          description?: string | null;
          default_days_per_year?: number;
          is_carry_forward?: boolean;
          max_carry_forward_days?: number;
          carry_forward_expiry_months?: number;
          accrual_frequency?: string | null;
          accrual_day?: number;
          min_notice_days?: number;
          max_consecutive_days?: number | null;
          is_half_day_allowed?: boolean;
          requires_document?: boolean;
          document_required_after_days?: number | null;
          requires_manager_approval?: boolean;
          requires_hr_approval?: boolean;
          applicable_gender?: string[] | null;
          is_paid?: boolean;
          pay_percentage?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          code?: string | null;
          type?: string;
          description?: string | null;
          default_days_per_year?: number;
          is_carry_forward?: boolean;
          max_carry_forward_days?: number;
          carry_forward_expiry_months?: number;
          accrual_frequency?: string | null;
          accrual_day?: number;
          min_notice_days?: number;
          max_consecutive_days?: number | null;
          is_half_day_allowed?: boolean;
          requires_document?: boolean;
          document_required_after_days?: number | null;
          requires_manager_approval?: boolean;
          requires_hr_approval?: boolean;
          applicable_gender?: string[] | null;
          is_paid?: boolean;
          pay_percentage?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      leave_requests: {
        Row: {
          id: string;
          employee_id: string;
          leave_type_id: string;
          company_id: string;
          start_date: string;
          end_date: string;
          start_half: boolean;
          end_half: boolean;
          total_days: number;
          reason: string;
          contact_number: string | null;
          emergency_contact: string | null;
          document_url: string | null;
          status: string;
          current_approver_id: string | null;
          current_approval_level: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          employee_id: string;
          leave_type_id: string;
          company_id: string;
          start_date: string;
          end_date: string;
          start_half?: boolean;
          end_half?: boolean;
          total_days: number;
          reason: string;
          contact_number?: string | null;
          emergency_contact?: string | null;
          document_url?: string | null;
          status?: string;
          current_approver_id?: string | null;
          current_approval_level?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          employee_id?: string;
          leave_type_id?: string;
          company_id?: string;
          start_date?: string;
          end_date?: string;
          start_half?: boolean;
          end_half?: boolean;
          total_days?: number;
          reason?: string;
          contact_number?: string | null;
          emergency_contact?: string | null;
          document_url?: string | null;
          status?: string;
          current_approver_id?: string | null;
          current_approval_level?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          reference_type: string | null;
          reference_id: string | null;
          is_read: boolean;
          read_at: string | null;
          email_sent: boolean;
          email_sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          reference_type?: string | null;
          reference_id?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          email_sent?: boolean;
          email_sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          reference_type?: string | null;
          reference_id?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          email_sent?: boolean;
          email_sent_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      calculate_leave_balance: {
        Args: {
          p_employee_id: string;
          p_leave_type_id: string;
          p_year: number;
        };
        Returns: number;
      };
      generate_claim_number: {
        Args: {
          p_company_id: string;
        };
        Returns: string;
      };
      generate_employee_code: {
        Args: {
          p_company_id: string;
          p_prefix?: string;
        };
        Returns: string;
      };
      get_working_days_in_month: {
        Args: {
          p_year: number;
          p_month: number;
          p_company_id: string;
          p_branch_id?: string;
        };
        Returns: number;
      };
    };
    Enums: {
      status_type: 'active' | 'inactive' | 'pending' | 'archived' | 'deleted';
      gender_type: 'male' | 'female' | 'other' | 'prefer_not_to_say';
      employment_type: 'full_time' | 'part_time' | 'contract' | 'intern' | 'temporary';
      leave_type_enum: 'annual' | 'sick' | 'personal' | 'maternity' | 'paternity' | 'emergency' | 'study' | 'unpaid' | 'custom';
      leave_status_enum: 'pending' | 'approved' | 'rejected' | 'cancelled' | 'revoked';
      attendance_status_enum: 'present' | 'absent' | 'late' | 'half_day' | 'work_from_home' | 'on_leave' | 'holiday';
      approval_status_enum: 'draft' | 'submitted' | 'pending_manager' | 'pending_hr' | 'approved' | 'rejected' | 'cancelled' | 'paid';
      salary_component_type: 'earning' | 'deduction';
      calculation_type: 'fixed' | 'percentage' | 'formula';
      payment_frequency_enum: 'monthly' | 'bi_weekly' | 'weekly';
      document_type_enum: 'contract' | 'certificate' | 'id_proof' | 'education' | 'experience' | 'other';
      day_of_week_enum: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
      claim_category_enum: 'transport' | 'accommodation' | 'meals' | 'fuel' | 'miscellaneous';
      payment_status_enum: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
      regularization_status_enum: 'pending' | 'approved' | 'rejected';
    };
  };
}

// Convenience types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T];

export type Row<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type Insert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type Update<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Specific table types for convenience
export type Company = Row<'companies'>;
export type CompanyAdmin = Row<'company_admins'>;
export type Profile = Row<'profiles'>;
export type Branch = Row<'branches'>;
export type Department = Row<'departments'>;
export type Designation = Row<'designations'>;
export type Role = Row<'roles'>;
export type Employee = Row<'employees'>;
export type Attendance = Row<'attendance'>;
export type LeaveType = Row<'leave_types'>;
export type LeaveRequest = Row<'leave_requests'>;
export type Notification = Row<'notifications'>;
